# Generated by Django 2.2.2 on 2019-06-20 03:40

import dev_test.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('breed', models.CharField(blank=True, choices=[('abyssinian', 'Abyssinian'), ('aegean', 'Aegean'), ('american-curl', 'American Curl'), ('american-bobtail', 'American Bobtail'), ('american-shorthair', 'American Shorthair'), ('american-wirehair', 'American Wirehair'), ('aphrodite-giant', 'Aphrodite Giant'), ('arabian-mau', 'Arabian Mau'), ('australian-mist', 'Australian Mist'), ('asian', 'Asian'), ('asian-semi-longhair', 'Asian Semi-longhair'), ('balinese', 'Balinese'), ('bambino', 'Bambino'), ('bengal', 'Bengal'), ('birman', 'Birman'), ('bombay', 'Bombay'), ('brazilian-shorthair', 'Brazilian Shorthair'), ('british-semi-longhair', 'British Semi-longhair'), ('british-shorthair', 'British Shorthair'), ('british-longhair', 'British Longhair'), ('burmese', 'Burmese'), ('burmilla', 'Burmilla'), ('california-spangled', 'California Spangled'), ('chantilly-tiffany', 'Chantilly Tiffany')], max_length=150, null=True, verbose_name='Breed')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to=dev_test.utils.upload_cat_image, verbose_name='Picture')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
