# Generated by Django 2.2.2 on 2019-06-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='image',
        ),
    ]
