# Generated by Django 2.2.2 on 2019-06-20 03:53

import dev_test.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20190620_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='cat',
            name='breed',
            field=models.CharField(blank=True, choices=[('abyssinian', 'Abyssinian'), ('aegean', 'Aegean'), ('american-curl', 'American Curl'), ('american-bobtail', 'American Bobtail'), ('american-shorthair', 'American Shorthair'), ('american-wirehair', 'American Wirehair'), ('aphrodite-giant', 'Aphrodite Giant'), ('arabian-mau', 'Arabian Mau'), ('australian-mist', 'Australian Mist'), ('asian', 'Asian'), ('asian-semi-longhair', 'Asian Semi-longhair'), ('balinese', 'Balinese'), ('bambino', 'Bambino'), ('bengal', 'Bengal'), ('birman', 'Birman'), ('bombay', 'Bombay'), ('brazilian-shorthair', 'Brazilian Shorthair'), ('british-semi-longhair', 'British Semi-longhair'), ('british-shorthair', 'British Shorthair'), ('british-longhair', 'British Longhair'), ('burmese', 'Burmese'), ('burmilla', 'Burmilla'), ('california-spangled', 'California Spangled'), ('chantilly-tiffany', 'Chantilly Tiffany')], max_length=150, null=True, verbose_name='Breed'),
        ),
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dev_test.utils.upload_cat_image, verbose_name='Picture'),
        ),
    ]
